import jsPDF from "jspdf";

export const downloadReport = async (data) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.text("AI PNEUMONIA DETECTION REPORT", 20, 20);

  // Line
  doc.line(20, 25, 190, 25);

  // Hospital
  doc.setFontSize(16);
  doc.text("Hospital Name", 20, 40);

  doc.setFontSize(12);
  doc.text("AI Powered Pneumonia Detection System", 20, 48);

  // Patient Details
  doc.setFontSize(16);
  doc.text("Patient Details", 20, 65);

  doc.setFontSize(12);

  doc.text(`Patient ID : ${data.patientId}`, 20, 75);
  doc.text(`Patient Name : ${data.patientName}`, 20, 83);
  doc.text(`Age : ${data.age}`, 20, 91);
  doc.text(`Gender : ${data.gender}`, 20, 99);
  doc.text(`Date : ${data.date}`, 20, 107);

  // Prediction
  doc.setFontSize(16);
  doc.text("Prediction", 20, 125);

  doc.setFontSize(12);
  doc.text(`Diagnosis : ${data.prediction}`, 20, 135);
  doc.text(`Confidence : ${data.confidence}%`, 20, 143);
  if (data.image) {
  const img = await loadImage(data.image);

  doc.setFontSize(15);
  doc.text("Chest X-Ray",20,160);

  doc.addImage(
    img,
    "JPEG",
    20,
    170,
    70,
    70
  );
}

if (data.heatmap) {

  const heat = await loadImage(data.heatmap);

  doc.setFontSize(15);

  doc.text("Grad-CAM Heatmap",110,160);

  doc.addImage(
      heat,
      "JPEG",
      110,
      170,
      70,
      70
  );

}

  // Doctor Notes
  doc.setFontSize(16);
  doc.text("Doctor Notes", 20, 165);

  doc.setFontSize(11);

  doc.text(
    [
      "• AI prediction should only be used as a second opinion.",
      "",
      "• Final diagnosis must be confirmed by",
      "  a qualified radiologist."
    ],
    20,
    175
  );

  // Footer
  doc.setFontSize(12);

  doc.text(
    "Generated by AI Pneumonia Detection System",
    20,
    260
  );

  doc.save(`Report_${data.patientId}.pdf`);
};
function loadImage(src) {

  return new Promise((resolve) => {

    const img = new Image();

    img.crossOrigin = "Anonymous";

    img.onload = () => {

      const canvas = document.createElement("canvas");

      canvas.width = img.width;

      canvas.height = img.height;

      const ctx = canvas.getContext("2d");

      ctx.drawImage(img,0,0);

      resolve(canvas.toDataURL("image/jpeg"));

    };

    img.src = src;

  });

}